name: Git Action for Repo Trigger

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Select Repository to Trigger'
        required: true
        type: choice
        options:
          - main
          - dev

jobs:
  trigger_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.event.inputs.repo_name }}
        
      - name: Get current branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "The currently checked out branch is: $CURRENT_BRANCH"
          
      - name: Set Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  
      - name: Get the current commit ID
        id: commit_id
        run: |
          echo "The commit ID is ${{ github.sha }}"

      - name: Save commit ID to a file inside logs folder
        run: |
          echo "Commit ID:${{ github.sha }}" >> commit-history/commit_ids.txt

      - name: Commit and push commit_ids.txt to the logs folder
        run: |
          git add commit-history/commit_ids.txt
          git commit -m "Add commit ID to commit-history/commit_ids.txt"
          git push origin HEAD

      - name: List repositories and display message
        run: |
          echo "You have selected to trigger repository: ${{ github.event.inputs.repo_name }}"

