name: Auto Deployment - Deploy based on changed files

on:
  push:
    paths:
      - 'project/*/deploy.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Read client list from clients.txt
        id: read_clients
        run: |
          # Read the clients from the clients.txt file and save them into an environment variable
          CLIENTS=$(cat ./project/deploy/auto/clients.txt | tr '\n' ',' | sed 's/,$//')
          echo "CLIENTS=$CLIENTS" >> $GITHUB_ENV
          echo "$CLIENTS"

      - name: Set execute permissions for deploy scripts
        run: |
          find ./project -name 'deploy.sh' -exec chmod +x {} \;

      - name: Deploy modified clients
        run: |
          # Get the list of modified files and extract the clients
          clients=$(echo "${{ steps.changed-files.outputs.all_modified_files }}" | grep -o 'project/[^/]\+/deploy.sh' | sed 's|/deploy.sh||')
          echo $clients
          # Loop through each client and deploy
          for client in $clients; do
            # Check if the client exists in the clients.txt list
            if echo "$CLIENTS" | grep -q "\b$client\b"; then
              echo "Deploying $client..."
              ./$client/deploy.sh
            else
              echo "Client $client not found in the clients list."
            fi
          done
