name: Manual Workflow with User Restriction, Commit ID, and Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to (e.g., staging or production)'
        required: true
        default: 'staging'
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'
      commit_id:
        description: 'Commit ID to rollback to (leave empty for the latest commit)'
        required: false
        default: ''  # If not specified, it will deploy the latest commit

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:        
    - name: Print GitHub Actor (GitHub username)
      run: |
        echo "GitHub Username (actor): ${{ github.actor }}"
    
    - name: Check if user is authorized
      run: |
        # Define allowed users (GitHub usernames)
        ALLOWED_USERS=("abinesan1" "user2" "user3")
        
        # Check if the current user (github.actor) is in the allowed users list
        if [[ ! " ${ALLOWED_USERS[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
          echo "You are not authorized to trigger this workflow."
          exit 1  # Fail the job if the user is not authorized
        fi
  
    # Step 1: Checkout the specific commit (either passed commit-id or latest commit)
    - name: Checkout code with specific commit ID
      uses: actions/checkout@v3
      with:
        # Use commit-id passed from workflow_dispatch or fallback to 'main'
        ref: ${{ github.event.inputs.commit_id || 'main' }}

    # Step 2: Set the COMMIT_ID environment variable
    - name: Get Git commit ID or use passed commit ID
      run: |
        if [ -z "${{ github.event.inputs.commit-id }}" ]; then
          COMMIT_ID=$(git rev-parse HEAD)  # Get current commit ID if no commit ID is passed
          echo "No commit ID passed, using current commit: $COMMIT_ID"
        else
          COMMIT_ID="${{ github.event.inputs.commit-id }}"
          # Remove any leading or trailing whitespace
          COMMIT_ID=$(echo $COMMIT_ID | xargs)
          echo "Using passed commit ID: $COMMIT_ID"
        fi
        echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV  # Store commit ID in environment variable

        
    - name: Display Commit ID
      run: |
        echo "The final COMMIT_ID is: ${{ env.COMMIT_ID }}"

    
        
    # - name: Checkout and Validate specific commit if provided, or latest commit
    #   run: |
    #     # If a commit_id is provided, validate that it is a valid commit hash
    #     if [[ -n "${{ github.event.inputs.commit_id }}" ]]; then
    #       COMMIT_ID="${{ github.event.inputs.commit_id }}"
    #       echo "Validating commit ID: $COMMIT_ID"
    
    #       # Remove any leading or trailing whitespace
    #       COMMIT_ID=$(echo $COMMIT_ID | xargs)
    
    #       # Validate if the commit ID is exactly 40 characters and contains only valid hexadecimal characters
    #       if [[ ! "$COMMIT_ID" =~ ^[0-9a-f]{40}$ ]]; then
    #         echo "Invalid commit ID: $COMMIT_ID. It must be a valid 40-character commit hash."
    #         exit 1  # Exit if the commit ID is invalid
    #       else
    #         echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV  # Store commit ID in environment variable
    #         echo "Git Roll back Commit ID: $COMMIT_ID"
    #         git checkout ${{ env.COMMIT_ID }}
    #       fi
    #     else
    #       echo "No commit ID provided. Checking out the latest commit (HEAD)."
    #     fi
        
    # - name: Print input values and commit ID
    #   run: |
    #     echo "Deploying to environment: ${{ github.event.inputs.environment }}"
    #     echo "Deploying version: ${{ github.event.inputs.version }}"
    #     echo "Git Commit ID: ${{ env.COMMIT_ID }}"  # Access the commit ID from the environment variable
    #     echo "Triggered by user: ${{ github.actor }}"  # Print the username who triggered the workflow
        
    - name: login to hub  
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: aibinesan/flaskapp:${{ env.COMMIT_ID }}    
    - name: deploying
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # sudo mkdir test.txt
          docker image pull aibinesan/flaskapp:${{ env.COMMIT_ID }}
          docker container stop flask
          docker container rm flask
          docker container run -d --name flask -p 80:5000 aibinesan/flaskapp:${{ env.COMMIT_ID }}
          

    # - name: Track current deployment and update rollback history
    #   run: |
    #     # Set the committer's name and email dynamically based on the GitHub context
    #     git config user.name "${{ github.actor }}"
    #     git config user.email "${{ github.actor }}@users.noreply.github.com"
        
    #     # Get the current commit ID and message
    #     CURRENT_COMMIT=$(git rev-parse HEAD)
    #     CURRENT_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
    #     CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')

    #     # Create or update rollback-history.txt file
    #     if [ -f rollback-history.txt ]; then
    #       echo "rollback-history.txt exists, adding to Git..."
    #     else
    #       echo "rollback-history.txt not found, creating new file..."
    #     fi

    #     # Log current deployment details and append date/time
    #     echo "Date: $CURRENT_DATE" >> rollback-history.txt
    #     echo "Current Commit: $CURRENT_COMMIT" >> rollback-history.txt
    #     echo "Commit Message: $CURRENT_COMMIT_MESSAGE" >> rollback-history.txt
    #     echo "Environment: ${{ github.event.inputs.environment }}" >> rollback-history.txt
    #     echo "Version: ${{ github.event.inputs.version }}" >> rollback-history.txt
        
    #     # Track changes in the repository by using git diff (to show what changed)
    #     CHANGES=$(git diff --name-status HEAD~1..HEAD)
    #     echo "Changes: $CHANGES" >> rollback-history.txt

    #     # Add the rollback-history.txt file to Git index
    #     git add rollback-history.txt

    #     # Commit the changes with a message
    #     git commit -m "Update rollback history with current deployment"

    #     # Push the changes back to the repository
    #     git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
